# Analysis_options.yaml
# Using Google Style Guide
include: package:pedantic/analysis_options.yaml

analyzer:
  exclude:
    - lib/generated/**
    - lib/view/
    - test/
  errors:
    missing_required_param: warning
    parameter_assignments: warning
    missing_return: warning
    todo: ignore

linter:
  rules:
    prefer_single_quotes: false
    omit_local_variable_types: false
    unnecessary_this: false
    unnecessary_null_comparison: false
    unrelated_type_equality_checks: false
    sort_child_properties_last: false
    prefer_generic_function_type_aliases: false
    prefer_final_fields: false
    annotate_overrides: false
    avoid_return_types_on_setters: false
    unused_element: false
    unused_field: false
    prefer_collection_literals: false
    must_be_immutable: false


