import 'package:plate_waste_recorder/Model/food_status.dart';
import 'package:plate_waste_recorder/Model/meal.dart';
import 'package:plate_waste_recorder/Model/meal_info.dart';
import 'package:test/test.dart';

// run tests from the terminal using: flutter test test/meal_test.dart
// if flutter.bat is not part of you PATH environment variable provide the absolute path
// to flutter.bat, for example use installationdirectory\flutter\bin\flutter test test/meal_test.dart
void main() {
  group("Meal getters and setters", () {
    test("Meal setters and getters", () {
      Meal testMeal = Meal("test meal", FoodStatus.uneaten, "testImageString",
          12.05, "test comment");
      // meal ids are randomly generated by default so we have no idea what this meal id
      // might be, check a few characteristics, that is not empty etc
      expect(testMeal.id.isNotEmpty, true);
      expect(testMeal.id != null, true);

      expect(testMeal.mealStatus, FoodStatus.uneaten);

      expect(testMeal.comment, "test comment");

      expect(testMeal.mealHasComment(), true);

      testMeal.comment = "new comment";

      expect(testMeal.comment, "new comment");

      MealInfo testMealInfo = testMeal.getMealInfo();

      expect(
          testMealInfo, MealInfo(testMeal.id, "test meal", FoodStatus.uneaten));
    });
  });
}
