name: Main actions file

on:
  pull_request:
    branches:
      - main
      - Development
      
  push:
    branches:
      - '*'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
      
      - name: install flutter dependencies
        run: flutter pub get
      
      - name: install dart dependencies
        run: dart pub get
      
      - run: flutter analyze .
        
      - name: run dart tests
        run: flutter test
