name: Main actions file

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
      
      - name: install flutter dependencies
        run: flutter packages get
        
      - name: install dart dependencies
        run: dart pub get
        
      - name: run dart tests
        run: dart test
        
