name: onPush

on:    
  push:
    branches:
      - '*'

jobs:
  tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
      
      - name: install flutter dependencies
        run: flutter pub get
      
      - name: install dart dependencies
        run: dart pub get

      - name: run dart tests
        run: flutter test --no-sound-null-safety
        
      - name: run smoke tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: flutter drive --driver=test/test_driver/integration_test_driver.dart --target=test/utils/run_integration_tests.dart --no-sound-null-safety

        
